default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= Rails.application.credentials.database[:username] %>
  password: <%= Rails.application.credentials.database[:password] %>
  host: <%= Rails.application.credentials.database[:host] %>
  port: <%= Rails.application.credentials.database[:port] %>
  database: <%= Rails.application.credentials.database[:db_name] %>
  pool: 5
development:
  <<: *default
test:
  <<: *default
production:
  <<: *default